/*
 * Copyright (C) 2019 lucasmeyer
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package panels.analisadorasset;

import java.awt.Color;

/**
 *
 * @author lucasmeyer
 */
public class analisadorasset extends javax.swing.JPanel
{
    //classe que segura os subitens do analisador de asset, ateh o momento estes itens sao
    //grafico (para analise tecnica)
    //trader, traderbot e interface para trades offlines
    
    //item analisador de asset ao qual este analisador esta associado
    public panels.analisadorasset.itemanalisadorasset iaassetpai;
    
    //submobulo grafico
    public panels.analisadorasset.grafico.submodulografico subgrafico;
    //submodulo trader
    public panels.analisadorasset.trader.submodulotrader subtrader;
    
    /**
     * Creates new form mpanalisadorasset
     */
    public analisadorasset(panels.analisadorasset.itemanalisadorasset iaapai)
    {
        initComponents();
        
        jPanelSubmodulosHolder.setLayout(new java.awt.GridLayout(1,1));
        
        //associar o item analisador asset a este analisador asset
        iaassetpai = iaapai;
        
        //criar submodulos grafico e trader para uso
        subgrafico = new panels.analisadorasset.grafico.submodulografico(this);
        subtrader = new panels.analisadorasset.trader.submodulotrader(this);
        
        mostrarsubmodulografico();
    }
    
    void mostrarsubmodulografico()
    {
        jPanelSubmodulosHolder.removeAll();
        
        //funcao para mostrar submodulo grafico
        jPanelSubmodulosHolder.add(subgrafico);
        jButtonMostrarGrafico.setForeground(Color.red);
        jButtonMostrarTrader.setForeground(Color.black);
        this.validate();
        this.repaint();
    }
    
    void mostrarsubmodulotrader()
    {
        jPanelSubmodulosHolder.removeAll();
        
        //funcao para mostrar submodulo grafico
        jPanelSubmodulosHolder.add(subtrader);
        jButtonMostrarTrader.setForeground(Color.red);
        jButtonMostrarGrafico.setForeground(Color.black);
        this.validate();
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanelSubmodulosHolder = new javax.swing.JPanel();
        jPanelEscolherSubmodulo = new javax.swing.JPanel();
        jButtonMostrarGrafico = new javax.swing.JButton();
        jButtonMostrarTrader = new javax.swing.JButton();

        jPanelSubmodulosHolder.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanelSubmodulosHolderLayout = new javax.swing.GroupLayout(jPanelSubmodulosHolder);
        jPanelSubmodulosHolder.setLayout(jPanelSubmodulosHolderLayout);
        jPanelSubmodulosHolderLayout.setHorizontalGroup(
            jPanelSubmodulosHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelSubmodulosHolderLayout.setVerticalGroup(
            jPanelSubmodulosHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 425, Short.MAX_VALUE)
        );

        jPanelEscolherSubmodulo.setBackground(new java.awt.Color(120, 120, 120));

        jButtonMostrarGrafico.setForeground(new java.awt.Color(255, 0, 0));
        jButtonMostrarGrafico.setText("Chart");
        jButtonMostrarGrafico.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonMostrarGraficoActionPerformed(evt);
            }
        });

        jButtonMostrarTrader.setText("Trader");
        jButtonMostrarTrader.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonMostrarTraderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelEscolherSubmoduloLayout = new javax.swing.GroupLayout(jPanelEscolherSubmodulo);
        jPanelEscolherSubmodulo.setLayout(jPanelEscolherSubmoduloLayout);
        jPanelEscolherSubmoduloLayout.setHorizontalGroup(
            jPanelEscolherSubmoduloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEscolherSubmoduloLayout.createSequentialGroup()
                .addComponent(jButtonMostrarGrafico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonMostrarTrader)
                .addContainerGap(491, Short.MAX_VALUE))
        );
        jPanelEscolherSubmoduloLayout.setVerticalGroup(
            jPanelEscolherSubmoduloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonMostrarGrafico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonMostrarTrader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelSubmodulosHolder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelEscolherSubmodulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelEscolherSubmodulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelSubmodulosHolder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMostrarGraficoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonMostrarGraficoActionPerformed
    {//GEN-HEADEREND:event_jButtonMostrarGraficoActionPerformed
        mostrarsubmodulografico();
    }//GEN-LAST:event_jButtonMostrarGraficoActionPerformed

    private void jButtonMostrarTraderActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonMostrarTraderActionPerformed
    {//GEN-HEADEREND:event_jButtonMostrarTraderActionPerformed
       mostrarsubmodulotrader();
    }//GEN-LAST:event_jButtonMostrarTraderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonMostrarGrafico;
    private javax.swing.JButton jButtonMostrarTrader;
    private javax.swing.JPanel jPanelEscolherSubmodulo;
    private javax.swing.JPanel jPanelSubmodulosHolder;
    // End of variables declaration//GEN-END:variables
}
