/*
 * Copyright (C) 2019 Lucas Meyer
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package panels.analisadorasset;

/**
 *
 * @author lucasmeyer
 */
public class itemanalisadorasset extends javax.swing.JPanel
{
    //jpanel que pertence a uma lista de simbolos que o usuario escolheu para uso
    
    //tela principal pai
    public main.TelaPrincipal tprincipalpai;
    
    //submodulo grafico associado a este item grafico
    //public panels.analisadorasset.grafico.submodulografico mpsubgrafico; 
    
    //analisadorasset associado a este item
    public panels.analisadorasset.analisadorasset aasset;
    
    //id deste grafico
    public String id;
    
    /**
     * Creates new form mpsimbolo
     */
    public itemanalisadorasset(main.TelaPrincipal tppai)
    {
        initComponents();

        id = "asset"+java.util.UUID.randomUUID().toString();
        
        //associar a tela principal a este itemanalisadorasset
        tprincipalpai = tppai;
        
        panels.analisadorasset.analisadorasset aa = new panels.analisadorasset.analisadorasset(this);
        aasset = aa;
        
        //criar um analisadorasset para associar a este itemanalisadorasset
        //panels.analisadorasset.analisadorasset aa = panels.analisadorasset.analisadorassetholder();
        
        /*
        panels.analisadorasset.analisadorasset aa = mierpanels.analisadorasset.analisadorasset(this);
        
        panels.analisadorasset.analisadorasset mpaa =        mierpanels.analisadorasset.aagrafico.mpaagrafico mpsmg = new panels.analisadorasset.grafico.submodulografico(this);
        mpsubgrafico = mpsmg;*/
    }
    
    public void renomearitem(String novonome)
    {
        jLabelNomeAnalisadorAsset.setText(novonome);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanelSub = new javax.swing.JPanel();
        jLabelNomeAnalisadorAsset = new javax.swing.JLabel();
        jLabelDeletarAnalisadorAsset = new javax.swing.JLabel();
        jLabelAbrirJanelaRenomearAnalisadorAsset = new javax.swing.JLabel();

        setBackground(new java.awt.Color(155, 155, 155));

        jPanelSub.setBackground(new java.awt.Color(55, 55, 55));
        jPanelSub.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                jPanelSubMousePressed(evt);
            }
        });

        jLabelNomeAnalisadorAsset.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNomeAnalisadorAsset.setText("New Asset");

        jLabelDeletarAnalisadorAsset.setForeground(new java.awt.Color(255, 0, 0));
        jLabelDeletarAnalisadorAsset.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDeletarAnalisadorAsset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/trashred.png"))); // NOI18N
        jLabelDeletarAnalisadorAsset.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jLabelDeletarAnalisadorAssetMouseClicked(evt);
            }
        });

        jLabelAbrirJanelaRenomearAnalisadorAsset.setForeground(new java.awt.Color(255, 255, 125));
        jLabelAbrirJanelaRenomearAnalisadorAsset.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAbrirJanelaRenomearAnalisadorAsset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/penyellow.png"))); // NOI18N
        jLabelAbrirJanelaRenomearAnalisadorAsset.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jLabelAbrirJanelaRenomearAnalisadorAssetMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelSubLayout = new javax.swing.GroupLayout(jPanelSub);
        jPanelSub.setLayout(jPanelSubLayout);
        jPanelSubLayout.setHorizontalGroup(
            jPanelSubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSubLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNomeAnalisadorAsset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelAbrirJanelaRenomearAnalisadorAsset)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelDeletarAnalisadorAsset)
                .addContainerGap())
        );
        jPanelSubLayout.setVerticalGroup(
            jPanelSubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSubLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNomeAnalisadorAsset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelSubLayout.createSequentialGroup()
                        .addGroup(jPanelSubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelAbrirJanelaRenomearAnalisadorAsset, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelDeletarAnalisadorAsset))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelSub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelSub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelSubMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSubMousePressed
        tprincipalpai.selecionarItemAnalisadorAsset(this);
    }//GEN-LAST:event_jPanelSubMousePressed

    private void jLabelDeletarAnalisadorAssetMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLabelDeletarAnalisadorAssetMouseClicked
    {//GEN-HEADEREND:event_jLabelDeletarAnalisadorAssetMouseClicked
        tprincipalpai.removerAnalisadorAsset(this);
    }//GEN-LAST:event_jLabelDeletarAnalisadorAssetMouseClicked

    private void jLabelAbrirJanelaRenomearAnalisadorAssetMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLabelAbrirJanelaRenomearAnalisadorAssetMouseClicked
    {//GEN-HEADEREND:event_jLabelAbrirJanelaRenomearAnalisadorAssetMouseClicked

        frames.analisadorasset.renomearitemanalisadorasset mfrig = new frames.analisadorasset.renomearitemanalisadorasset(this);
        mfrig.show();
    }//GEN-LAST:event_jLabelAbrirJanelaRenomearAnalisadorAssetMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelAbrirJanelaRenomearAnalisadorAsset;
    private javax.swing.JLabel jLabelDeletarAnalisadorAsset;
    public javax.swing.JLabel jLabelNomeAnalisadorAsset;
    public javax.swing.JPanel jPanelSub;
    // End of variables declaration//GEN-END:variables
}
