/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mierframes;


/**
 *
 * @author lucasmeyer
 */
public class mfadicionarsimbolo extends javax.swing.JFrame
{
    public static mierpanels.mpsubmodulografico submodulopai;
    java.util.List<mierclasses.mcavsearchresultcandle> listaatualbm;
    
    /**
     * Creates new form WindowAdicionarSimbolo
     */
    public mfadicionarsimbolo(mierpanels.mpsubmodulografico smodpai)
    {
        initComponents();
        
        submodulopai = smodpai;
        
        modellistasimbolosencontrados = new javax.swing.DefaultListModel();
        jlistSimbolosEncontrados.setModel(modellistasimbolosencontrados);
    }

    javax.swing.DefaultListModel modellistasimbolosencontrados;
    void procurarsimbolosemostrarnalista()
    {
        listaatualbm = submodulopai.mtgraficopai.tprincipalpai.mav.receberstocksearchbestmatches(jtfProcurarSimbolo.getText());

        modellistasimbolosencontrados.removeAllElements();
        for (int i = 0; i < listaatualbm.size(); i++)
        {
            mierclasses.mcavsearchresultcandle bmatual = listaatualbm.get(i);
            //mierclasses.mierfuncoeshelper.mostrarmensagem(bmatual.namestr);

            modellistasimbolosencontrados.addElement("[" + bmatual.symbolstr + "|"+ bmatual.regionstr +"] " + bmatual.namestr);
        }
        jlistSimbolosEncontrados.setSelectedIndex(0);
    }
    
    void adicionarsimboloprograma()
    {
        submodulopai.adicionarsimboloaotextboxsubmodulo(listaatualbm.get(jlistSimbolosEncontrados.getSelectedIndex()));
        this.dispose();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel2 = new javax.swing.JLabel();
        jtfProcurarSimbolo = new javax.swing.JTextField();
        jbProcurarSimbolo = new javax.swing.JButton();
        jbAdicionarSimbolo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlistSimbolosEncontrados = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Adicionar Novo Símbolo");

        jLabel2.setText("Procurar");

        jbProcurarSimbolo.setText("OK");
        jbProcurarSimbolo.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jbProcurarSimboloActionPerformed(evt);
            }
        });

        jbAdicionarSimbolo.setText("Adicionar");
        jbAdicionarSimbolo.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jbAdicionarSimboloActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jlistSimbolosEncontrados);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfProcurarSimbolo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbProcurarSimbolo))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbAdicionarSimbolo)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfProcurarSimbolo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbProcurarSimbolo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbAdicionarSimbolo)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbProcurarSimboloActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jbProcurarSimboloActionPerformed
    {//GEN-HEADEREND:event_jbProcurarSimboloActionPerformed
        procurarsimbolosemostrarnalista();
    }//GEN-LAST:event_jbProcurarSimboloActionPerformed

    private void jbAdicionarSimboloActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jbAdicionarSimboloActionPerformed
    {//GEN-HEADEREND:event_jbAdicionarSimboloActionPerformed
        adicionarsimboloprograma();
    }//GEN-LAST:event_jbAdicionarSimboloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(mfadicionarsimbolo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(mfadicionarsimbolo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(mfadicionarsimbolo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(mfadicionarsimbolo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new mfadicionarsimbolo(submodulopai).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAdicionarSimbolo;
    private javax.swing.JButton jbProcurarSimbolo;
    private javax.swing.JList<String> jlistSimbolosEncontrados;
    private javax.swing.JTextField jtfProcurarSimbolo;
    // End of variables declaration//GEN-END:variables
}
