/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mierframes;

import java.io.File;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;

/**
 *
 * @author lucasmeyer
 */
public class mfconfiguracoesgerais extends javax.swing.JFrame
{

    /**
     * Creates new form mfconfiguracoesgerais
     */
    public mfconfiguracoesgerais()
    {
        initComponents();
        inicializarjanelaconfiguracao();
    }
    
    void inicializarjanelaconfiguracao()
    {
                //abrir documento /arquivosconfig/indicadores.mfxconfig para ler indicadores disponiveis para uso
        //e criar itens com indicadores disponiveis no jComboBoxIndicadoresDisponiveis
        
        try
        {
            String rootjar = mierclasses.mcfuncoeshelper.retornarpathbaseprograma();
            String cgeneralconfig = rootjar + "/configfiles/general.mfxconfig";
            //mierclasses.mcfuncoeshelper.mostrarmensagem(cindicconfig);
            
            File xmlArquivo = new File(cgeneralconfig);
            DocumentBuilderFactory dbfactory = DocumentBuilderFactory.newInstance();
        
            DocumentBuilder dbuilder = dbfactory.newDocumentBuilder();
        
            Document document = dbuilder.parse(xmlArquivo);
            
            String avkey = document.getElementsByTagName("AVKEY").item(0).getTextContent();
            jTextFieldNewAvkey.setText(avkey);
        }
        catch (Exception e) 
        {
            mierclasses.mcfuncoeshelper.mostrarmensagem("Uma exceção ocorreu: " + e.toString());
        }
    }
    
    void atualizaravkey()
    {
        try
        {
          String generalxmlatualizar = 
                "<?xml version=\"1.0\"?>" +
                    "<OpenstockGeneralConfiguration>" +
                    "<AVKEY>"+jTextFieldNewAvkey.getText()+"</AVKEY>" +
                   "</OpenstockGeneralConfiguration>";
        

        String rootjar = mierclasses.mcfuncoeshelper.retornarpathbaseprograma();
        String cgeneralconfig = rootjar + "/configfiles/general.mfxconfig";
        File xmlArquivoConfigGeral = new File(cgeneralconfig);

        java.io.PrintWriter writer = new java.io.PrintWriter(xmlArquivoConfigGeral, "UTF-8");
        writer.println(generalxmlatualizar);
        writer.close();   
        
        mierclasses.mcfuncoeshelper.mostrarmensagem("Alpha Vantage Key has been updated. Please restart Open Stock to use it.");
        this.dispose();
        
        }
        catch (Exception ex)
        {
            mierclasses.mcfuncoeshelper.mostrarmensagem("A problem occurred. Exception: " + ex.getMessage());
        }
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabelAvkey = new javax.swing.JLabel();
        jTextFieldNewAvkey = new javax.swing.JTextField();
        jButtonUpdateAvkey = new javax.swing.JButton();
        jLabelAbout = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("General Configuration");

        jLabelAvkey.setText("Alpha Vantage Key:");

        jButtonUpdateAvkey.setText("Update");
        jButtonUpdateAvkey.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonUpdateAvkeyActionPerformed(evt);
            }
        });

        jLabelAbout.setFont(new java.awt.Font("Lucida Grande", 2, 10)); // NOI18N
        jLabelAbout.setText("Open Stock (Alpha Vantage v. 1.0a)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelAvkey)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNewAvkey))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelAbout)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                        .addComponent(jButtonUpdateAvkey)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAvkey)
                    .addComponent(jTextFieldNewAvkey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonUpdateAvkey)
                    .addComponent(jLabelAbout))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonUpdateAvkeyActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonUpdateAvkeyActionPerformed
    {//GEN-HEADEREND:event_jButtonUpdateAvkeyActionPerformed
        atualizaravkey();
    }//GEN-LAST:event_jButtonUpdateAvkeyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(mfconfiguracoesgerais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(mfconfiguracoesgerais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(mfconfiguracoesgerais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(mfconfiguracoesgerais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new mfconfiguracoesgerais().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonUpdateAvkey;
    private javax.swing.JLabel jLabelAbout;
    private javax.swing.JLabel jLabelAvkey;
    private javax.swing.JTextField jTextFieldNewAvkey;
    // End of variables declaration//GEN-END:variables
}
