/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mierframes;

import java.io.File;


/**
 *
 * @author lucasmeyer
 */
public class mfconfiguracoes extends javax.swing.JFrame
{
public static mierstockfx.TelaPrincipal telappai;
    
    /**
     * Creates new form mfconfiguracoesgerais
     */
    public mfconfiguracoes(mierstockfx.TelaPrincipal tppai)
    {
        initComponents();
        
        telappai = tppai;
        
        //adicionar
        jButtonAddRemoveIndicators.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelMore = new javax.swing.JPanel();
        jButtonAddRemoveIndicators = new javax.swing.JButton();
        jButtonOpenBearcodeEditor = new javax.swing.JButton();
        jPanelAbout = new javax.swing.JPanel();
        jLabelOpenStock = new javax.swing.JLabel();
        jLabelLastBuild = new javax.swing.JLabel();
        jLabelBear = new javax.swing.JLabel();
        jLabelVersion = new javax.swing.JLabel();
        jLabelAPIAttribution = new javax.swing.JLabel();
        jButtonGithub = new javax.swing.JButton();
        jButtonIEX = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Options");

        jPanelMore.setBackground(new java.awt.Color(55, 55, 55));

        jButtonAddRemoveIndicators.setText("Add and Remove Indicators");
        jButtonAddRemoveIndicators.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddRemoveIndicatorsActionPerformed(evt);
            }
        });

        jButtonOpenBearcodeEditor.setText("Bearcode Editor");
        jButtonOpenBearcodeEditor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpenBearcodeEditorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMoreLayout = new javax.swing.GroupLayout(jPanelMore);
        jPanelMore.setLayout(jPanelMoreLayout);
        jPanelMoreLayout.setHorizontalGroup(
            jPanelMoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMoreLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonOpenBearcodeEditor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAddRemoveIndicators, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelMoreLayout.setVerticalGroup(
            jPanelMoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMoreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonOpenBearcodeEditor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAddRemoveIndicators)
                .addContainerGap(107, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("More", jPanelMore);

        jPanelAbout.setBackground(new java.awt.Color(55, 55, 55));

        jLabelOpenStock.setForeground(new java.awt.Color(255, 255, 255));
        jLabelOpenStock.setText("Open Stock");

        jLabelLastBuild.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLastBuild.setText("(Lucas Meyer build - January 2019)");

        jLabelBear.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/bear70.png"))); // NOI18N

        jLabelVersion.setForeground(new java.awt.Color(255, 255, 255));
        jLabelVersion.setText("Version: iex1.02a");

        jLabelAPIAttribution.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAPIAttribution.setText("API Attribution: Data provided for free by IEX. View IEX’s Terms of Use.");

        jButtonGithub.setText("Open Stock's GitHub");
        jButtonGithub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGithubActionPerformed(evt);
            }
        });

        jButtonIEX.setText("IEX's Terms of Use");
        jButtonIEX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIEXActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAboutLayout = new javax.swing.GroupLayout(jPanelAbout);
        jPanelAbout.setLayout(jPanelAboutLayout);
        jPanelAboutLayout.setHorizontalGroup(
            jPanelAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAboutLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAboutLayout.createSequentialGroup()
                        .addGroup(jPanelAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelAboutLayout.createSequentialGroup()
                                .addComponent(jLabelOpenStock)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelVersion))
                            .addComponent(jLabelLastBuild))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelBear, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelAPIAttribution, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelAboutLayout.createSequentialGroup()
                        .addComponent(jButtonGithub)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonIEX)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelAboutLayout.setVerticalGroup(
            jPanelAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAboutLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelBear)
                    .addGroup(jPanelAboutLayout.createSequentialGroup()
                        .addGroup(jPanelAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelOpenStock)
                            .addComponent(jLabelVersion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelLastBuild)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jLabelAPIAttribution)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGithub)
                    .addComponent(jButtonIEX))
                .addContainerGap())
        );

        jTabbedPane1.addTab("About", jPanelAbout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGithubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGithubActionPerformed
        try
        {
            java.awt.Desktop.getDesktop().browse(new java.net.URI("https://github.com/lcmeyer37/openstock"));
        }
        catch (Exception ex)
        {
            mierclasses.mcfuncoeshelper.mostrarmensagem("A problem occurred. Exception: " + ex.getMessage());
        }
    }//GEN-LAST:event_jButtonGithubActionPerformed

    private void jButtonIEXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIEXActionPerformed
        try
        {
            java.awt.Desktop.getDesktop().browse(new java.net.URI("https://iextrading.com/api-exhibit-a/"));
        }
        catch (Exception ex)
        {
            mierclasses.mcfuncoeshelper.mostrarmensagem("A problem occurred. Exception: " + ex.getMessage());
        }
    }//GEN-LAST:event_jButtonIEXActionPerformed

    private void jButtonAddRemoveIndicatorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddRemoveIndicatorsActionPerformed
        //open interface to add and remove indicators
    }//GEN-LAST:event_jButtonAddRemoveIndicatorsActionPerformed

    private void jButtonOpenBearcodeEditorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpenBearcodeEditorActionPerformed
        //open interface to edit bearcode scripts
        mierframes.mfeditorbearcode mfebc = new mierframes.mfeditorbearcode(telappai);
        mfebc.show();
    }//GEN-LAST:event_jButtonOpenBearcodeEditorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(mfconfiguracoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(mfconfiguracoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(mfconfiguracoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(mfconfiguracoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new mfconfiguracoes(telappai).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddRemoveIndicators;
    private javax.swing.JButton jButtonGithub;
    private javax.swing.JButton jButtonIEX;
    private javax.swing.JButton jButtonOpenBearcodeEditor;
    private javax.swing.JLabel jLabelAPIAttribution;
    private javax.swing.JLabel jLabelBear;
    private javax.swing.JLabel jLabelLastBuild;
    private javax.swing.JLabel jLabelOpenStock;
    private javax.swing.JLabel jLabelVersion;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelAbout;
    private javax.swing.JPanel jPanelMore;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
