/*
 * Copyright (C) 2019 Lucas Meyer
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package analisadorasset;

/**
 *
 * @author meyerlu
 */
public class panel_noassetsmensagem extends javax.swing.JPanel
{
    public panel_noassetsmensagem()
    {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanelEscolherSubmodulo = new javax.swing.JPanel();
        jLabelWelcome = new javax.swing.JLabel();
        jLabelDistribution = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaWelcome = new javax.swing.JTextArea();
        jLabelToStart = new javax.swing.JLabel();
        jButtonLicense = new javax.swing.JButton();
        jButtonGithub = new javax.swing.JButton();
        jLabelDistribution1 = new javax.swing.JLabel();

        jPanelEscolherSubmodulo.setBackground(new java.awt.Color(25, 25, 25));

        jLabelWelcome.setBackground(new java.awt.Color(230, 230, 230));
        jLabelWelcome.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabelWelcome.setForeground(new java.awt.Color(200, 200, 200));
        jLabelWelcome.setText("Welcome to Open Stock!");

        jLabelDistribution.setBackground(new java.awt.Color(230, 230, 230));
        jLabelDistribution.setForeground(new java.awt.Color(200, 200, 200));
        jLabelDistribution.setText("Distribution: 1.035c");

        jTextAreaWelcome.setEditable(false);
        jTextAreaWelcome.setBackground(new java.awt.Color(25, 25, 25));
        jTextAreaWelcome.setColumns(20);
        jTextAreaWelcome.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jTextAreaWelcome.setForeground(new java.awt.Color(230, 230, 230));
        jTextAreaWelcome.setRows(5);
        jTextAreaWelcome.setText("Latest Release: 1.035\n\nOpen Stock Features:\n\n* Real-time data for multiple assets: stocks, dividends, indexes, forex, cryptocurrency\n* Possibility to analyze multiple charts at the same time\n* Use of Annotations and Indicators for Technical Analysis\n* Use of Robots to test automatic Algorithmic Trading\n* To create your own Indicators to use with the software (Bearcode Scripts)\n* To create your own Trader Bots algorithms to use with the software (Bearcode Scripts)\n* To test the efficacy of algorithms with the Bots Editor and History Trading Simulator\n* Save/Load Charts and Offline Transactions\n* Export .csv files for spreadsheets tracking\n* OHLC and Separate Indicator charts\n* Offline Trading\n* Telegram Bots for private notifications\n\nData and functionality provided for free by:\n\n* IEX\n* Alpha Vantage\n* CryptoCompare\n* Telegram API\n\n\n\n\n");
        jTextAreaWelcome.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextAreaWelcome.setCaretPosition(0);
        jScrollPane1.setViewportView(jTextAreaWelcome);

        jLabelToStart.setBackground(new java.awt.Color(230, 230, 230));
        jLabelToStart.setForeground(new java.awt.Color(200, 200, 200));
        jLabelToStart.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelToStart.setText("To start, click on the \"Add\" button to analyze a new asset.");

        jButtonLicense.setText("Open Stock License");
        jButtonLicense.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonLicenseActionPerformed(evt);
            }
        });

        jButtonGithub.setText("Open Stock's GitHub");
        jButtonGithub.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonGithubActionPerformed(evt);
            }
        });

        jLabelDistribution1.setBackground(new java.awt.Color(230, 230, 230));
        jLabelDistribution1.setForeground(new java.awt.Color(200, 200, 200));
        jLabelDistribution1.setText("Open Source Technical Analysis and Offline Trading Software");

        javax.swing.GroupLayout jPanelEscolherSubmoduloLayout = new javax.swing.GroupLayout(jPanelEscolherSubmodulo);
        jPanelEscolherSubmodulo.setLayout(jPanelEscolherSubmoduloLayout);
        jPanelEscolherSubmoduloLayout.setHorizontalGroup(
            jPanelEscolherSubmoduloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEscolherSubmoduloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEscolherSubmoduloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEscolherSubmoduloLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonLicense)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonGithub))
                    .addGroup(jPanelEscolherSubmoduloLayout.createSequentialGroup()
                        .addComponent(jLabelDistribution)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 195, Short.MAX_VALUE)
                        .addComponent(jLabelToStart))
                    .addGroup(jPanelEscolherSubmoduloLayout.createSequentialGroup()
                        .addGroup(jPanelEscolherSubmoduloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelWelcome)
                            .addComponent(jLabelDistribution1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelEscolherSubmoduloLayout.setVerticalGroup(
            jPanelEscolherSubmoduloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEscolherSubmoduloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelWelcome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDistribution1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEscolherSubmoduloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDistribution)
                    .addComponent(jLabelToStart))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEscolherSubmoduloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGithub)
                    .addComponent(jButtonLicense))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelEscolherSubmodulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 467, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelEscolherSubmodulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLicenseActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonLicenseActionPerformed
    {//GEN-HEADEREND:event_jButtonLicenseActionPerformed
        main.frame_license mfl = new main.frame_license();
        mfl.show();
    }//GEN-LAST:event_jButtonLicenseActionPerformed

    private void jButtonGithubActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonGithubActionPerformed
    {//GEN-HEADEREND:event_jButtonGithubActionPerformed
        try
        {
            java.awt.Desktop.getDesktop().browse(new java.net.URI("https://github.com/lcmeyer37/openstock"));
        }
        catch (Exception ex)
        {
            mierclasses.mcfuncoeshelper.mostrarmensagem("A problem occurred. Exception: " + ex.getMessage());
        }
    }//GEN-LAST:event_jButtonGithubActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGithub;
    private javax.swing.JButton jButtonLicense;
    private javax.swing.JLabel jLabelDistribution;
    private javax.swing.JLabel jLabelDistribution1;
    private javax.swing.JLabel jLabelToStart;
    private javax.swing.JLabel jLabelWelcome;
    private javax.swing.JPanel jPanelEscolherSubmodulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaWelcome;
    // End of variables declaration//GEN-END:variables
}
