/*
 * Copyright (C) 2019 Lucas Meyer
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package analisadorasset;

/**
 *
 * @author meyerlu
 */
public class panel_shjanelamensagem extends javax.swing.JPanel
{
    //classe utilizada para apresentar uma mensagem que os submodulos estao em uma janela separada
    analisadorasset.panel_analisadorasset aassetpai;
    
    /**
     * Creates new form janelasuspensamensagem
     */
    public panel_shjanelamensagem(analisadorasset.panel_analisadorasset aapai)
    {
        initComponents();
        
        aassetpai = aapai;
    }
    
    void mostrarsubmodulosholder()
    {
        aassetpai.atachsubmodulosholder();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanelEscolherSubmodulo = new javax.swing.JPanel();
        jLabelJanelaSuspensa = new javax.swing.JLabel();

        jPanelEscolherSubmodulo.setBackground(new java.awt.Color(25, 25, 25));

        jLabelJanelaSuspensa.setForeground(new java.awt.Color(255, 255, 255));
        jLabelJanelaSuspensa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelJanelaSuspensa.setText("Asset in Separate Window (Click to bind)");
        jLabelJanelaSuspensa.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jLabelJanelaSuspensaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelEscolherSubmoduloLayout = new javax.swing.GroupLayout(jPanelEscolherSubmodulo);
        jPanelEscolherSubmodulo.setLayout(jPanelEscolherSubmoduloLayout);
        jPanelEscolherSubmoduloLayout.setHorizontalGroup(
            jPanelEscolherSubmoduloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEscolherSubmoduloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelJanelaSuspensa, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelEscolherSubmoduloLayout.setVerticalGroup(
            jPanelEscolherSubmoduloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEscolherSubmoduloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelJanelaSuspensa, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 573, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelEscolherSubmodulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 455, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelEscolherSubmodulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelJanelaSuspensaMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLabelJanelaSuspensaMouseClicked
    {//GEN-HEADEREND:event_jLabelJanelaSuspensaMouseClicked
        mostrarsubmodulosholder();
    }//GEN-LAST:event_jLabelJanelaSuspensaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelJanelaSuspensa;
    private javax.swing.JPanel jPanelEscolherSubmodulo;
    // End of variables declaration//GEN-END:variables
}
