/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mierpanels;

/**
 *
 * @author lucasmeyer
 */
public class mpitemgrafico extends javax.swing.JPanel
{
    //jpanel que pertence a uma lista de simbolos que o usuario escolheu para uso
    
    //tela principal pai
    public mierstockfx.TelaPrincipal tprincipalpai;
    
    //submodulo grafico associado a este item grafico
    public mierpanels.mpsubmodulografico mpsubgrafico; 
    
    //id deste grafico
    public String id;
    
    /**
     * Creates new form mpsimbolo
     */
    public mpitemgrafico(mierstockfx.TelaPrincipal tppai)
    {
        initComponents();

        id = "asset"+java.util.UUID.randomUUID().toString();
        
        //associar a tela principal a este mpitemgrafico
        tprincipalpai = tppai;
        
        //criar um mpsubmodulografico para associar a este mpitemgrafico
        mierpanels.mpsubmodulografico mpsmg = new mierpanels.mpsubmodulografico(this);
        mpsubgrafico = mpsmg;
    }
    
    public void renomearitem(String novonome)
    {
        jLabelNomeItemGrafico.setText(novonome);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanelSub = new javax.swing.JPanel();
        jLabelNomeItemGrafico = new javax.swing.JLabel();
        jLabelAbrirDeletarGrafico = new javax.swing.JLabel();
        jLabelAbrirJanelaRenomearItemGrafico = new javax.swing.JLabel();

        setBackground(new java.awt.Color(155, 155, 155));

        jPanelSub.setBackground(new java.awt.Color(55, 55, 55));
        jPanelSub.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                jPanelSubMousePressed(evt);
            }
        });

        jLabelNomeItemGrafico.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNomeItemGrafico.setText("New Asset");

        jLabelAbrirDeletarGrafico.setForeground(new java.awt.Color(255, 0, 0));
        jLabelAbrirDeletarGrafico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAbrirDeletarGrafico.setText("D");
        jLabelAbrirDeletarGrafico.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jLabelAbrirDeletarGraficoMouseClicked(evt);
            }
        });

        jLabelAbrirJanelaRenomearItemGrafico.setForeground(new java.awt.Color(255, 255, 125));
        jLabelAbrirJanelaRenomearItemGrafico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAbrirJanelaRenomearItemGrafico.setText("R");
        jLabelAbrirJanelaRenomearItemGrafico.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jLabelAbrirJanelaRenomearItemGraficoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelSubLayout = new javax.swing.GroupLayout(jPanelSub);
        jPanelSub.setLayout(jPanelSubLayout);
        jPanelSubLayout.setHorizontalGroup(
            jPanelSubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSubLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNomeItemGrafico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelAbrirJanelaRenomearItemGrafico, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelAbrirDeletarGrafico, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelSubLayout.setVerticalGroup(
            jPanelSubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSubLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNomeItemGrafico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelSubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelAbrirDeletarGrafico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelAbrirJanelaRenomearItemGrafico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelSub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelSub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelSubMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSubMousePressed
tprincipalpai.selecionarItemGrafico(this);
    }//GEN-LAST:event_jPanelSubMousePressed

    private void jLabelAbrirDeletarGraficoMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLabelAbrirDeletarGraficoMouseClicked
    {//GEN-HEADEREND:event_jLabelAbrirDeletarGraficoMouseClicked
        tprincipalpai.removerGrafico(this);
    }//GEN-LAST:event_jLabelAbrirDeletarGraficoMouseClicked

    private void jLabelAbrirJanelaRenomearItemGraficoMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLabelAbrirJanelaRenomearItemGraficoMouseClicked
    {//GEN-HEADEREND:event_jLabelAbrirJanelaRenomearItemGraficoMouseClicked

        mierframes.mfrenomearitemgrafico mfrig = new mierframes.mfrenomearitemgrafico(this);
        mfrig.show();
    }//GEN-LAST:event_jLabelAbrirJanelaRenomearItemGraficoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelAbrirDeletarGrafico;
    private javax.swing.JLabel jLabelAbrirJanelaRenomearItemGrafico;
    public javax.swing.JLabel jLabelNomeItemGrafico;
    public javax.swing.JPanel jPanelSub;
    // End of variables declaration//GEN-END:variables
}
