/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mierpanels;

/**
 *
 * @author lucasmeyer
 */
public class mpitemanotacao extends javax.swing.JPanel
{
    //item utilizado para mostrar anotacoes introduzidas no grafico
    
    //submodulo grafico ao qual este item anotacao pertence
    public mierpanels.mpsubmodulografico submodulografico;
    
    //variavel que diz que tipo de anotacao eh esta, ex: linha, fibonacci, etc.
    public String tipoanotacao;
    
    //lista de subanotacoes desta anotacao para carregamento futuro
    //(public java.list.util.List<org.jfree.chart.annotations.XYAnnotation>)
    public java.util.List<org.jfree.chart.annotations.XYAnnotation> subannotationsanotacao;
    
    //id desta anotacao (utilizado para delecao)
    public String id;
    
    //construtor nova anotacao
    public mpitemanotacao(mierpanels.mpsubmodulografico smg, String tipo, java.util.List<org.jfree.chart.annotations.XYAnnotation> subans)
    {
        initComponents();
        
        id = "annotation"+java.util.UUID.randomUUID().toString();
        
        submodulografico = smg;
        tipoanotacao = tipo;
        subannotationsanotacao = subans;
    }
    
    //construtor recarregar anotacao
    public mpitemanotacao(mierpanels.mpsubmodulografico smg, String nome, String idan, String tipo, java.util.List<org.jfree.chart.annotations.XYAnnotation> subans)
    {
        initComponents();
        
        id = idan;
        
        jLabelNomeItemAnotacao.setText(nome);
        
        submodulografico = smg;
        tipoanotacao = tipo;
        subannotationsanotacao = subans;
    }
   
    
    public void renomearitem(String novonome)
    {
        if (tipoanotacao.equals("text"))
        {
            //caso seja anotacao, tambem renomear a anotacao no grafico em si
            org.jfree.chart.annotations.XYTextAnnotation antexto = (org.jfree.chart.annotations.XYTextAnnotation)subannotationsanotacao.get(0);
            antexto.setText(novonome);
        }
        jLabelNomeItemAnotacao.setText(novonome);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanelSub = new javax.swing.JPanel();
        jLabelNomeItemAnotacao = new javax.swing.JLabel();
        jLabelRemoverAnotacao = new javax.swing.JLabel();
        jLabelAbrirJanelaRenomearItemAnotacao = new javax.swing.JLabel();

        setBackground(new java.awt.Color(155, 155, 155));

        jPanelSub.setBackground(new java.awt.Color(55, 55, 55));

        jLabelNomeItemAnotacao.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNomeItemAnotacao.setText("New Annotation");

        jLabelRemoverAnotacao.setForeground(new java.awt.Color(255, 0, 0));
        jLabelRemoverAnotacao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRemoverAnotacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/trashred.png"))); // NOI18N
        jLabelRemoverAnotacao.setMaximumSize(new java.awt.Dimension(20, 20));
        jLabelRemoverAnotacao.setMinimumSize(new java.awt.Dimension(20, 20));
        jLabelRemoverAnotacao.setPreferredSize(new java.awt.Dimension(20, 20));
        jLabelRemoverAnotacao.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jLabelRemoverAnotacaoMouseClicked(evt);
            }
        });

        jLabelAbrirJanelaRenomearItemAnotacao.setForeground(new java.awt.Color(255, 255, 125));
        jLabelAbrirJanelaRenomearItemAnotacao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAbrirJanelaRenomearItemAnotacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/penyellow.png"))); // NOI18N
        jLabelAbrirJanelaRenomearItemAnotacao.setMaximumSize(new java.awt.Dimension(20, 20));
        jLabelAbrirJanelaRenomearItemAnotacao.setMinimumSize(new java.awt.Dimension(20, 20));
        jLabelAbrirJanelaRenomearItemAnotacao.setPreferredSize(new java.awt.Dimension(20, 20));
        jLabelAbrirJanelaRenomearItemAnotacao.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jLabelAbrirJanelaRenomearItemAnotacaoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelSubLayout = new javax.swing.GroupLayout(jPanelSub);
        jPanelSub.setLayout(jPanelSubLayout);
        jPanelSubLayout.setHorizontalGroup(
            jPanelSubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSubLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNomeItemAnotacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelAbrirJanelaRenomearItemAnotacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelRemoverAnotacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelSubLayout.setVerticalGroup(
            jPanelSubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSubLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelNomeItemAnotacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelSubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabelAbrirJanelaRenomearItemAnotacao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelRemoverAnotacao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelAbrirJanelaRenomearItemAnotacao.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelSub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelSub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelAbrirJanelaRenomearItemAnotacaoMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLabelAbrirJanelaRenomearItemAnotacaoMouseClicked
    {//GEN-HEADEREND:event_jLabelAbrirJanelaRenomearItemAnotacaoMouseClicked
        mierframes.mfrenomearitemanotacao mfrig = new mierframes.mfrenomearitemanotacao(this);
        mfrig.show();
    }//GEN-LAST:event_jLabelAbrirJanelaRenomearItemAnotacaoMouseClicked

    private void jLabelRemoverAnotacaoMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLabelRemoverAnotacaoMouseClicked
    {//GEN-HEADEREND:event_jLabelRemoverAnotacaoMouseClicked
        submodulografico.removerAnotacao(this);
    }//GEN-LAST:event_jLabelRemoverAnotacaoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelAbrirJanelaRenomearItemAnotacao;
    public javax.swing.JLabel jLabelNomeItemAnotacao;
    private javax.swing.JLabel jLabelRemoverAnotacao;
    private javax.swing.JPanel jPanelSub;
    // End of variables declaration//GEN-END:variables
}
