/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mierpanels;

/**
 *
 * @author lucasmeyer
 */
public class mpitemanotacao extends javax.swing.JPanel
{
    //item utilizado para mostrar anotacoes introduzidas no grafico
    
    //submodulo grafico ao qual este item anotacao pertence
    public mierpanels.mpsubmodulografico submodulografico;
    //xyannotation relacionado a este item
    public org.jfree.chart.annotations.XYAnnotation xyannotation;
    
    //id desta anotacao
    String id;
    
    
    /**
     * Creates new form mpsimbolo
     */
    public mpitemanotacao(mierpanels.mpsubmodulografico smg, org.jfree.chart.annotations.XYAnnotation anot)
    {
        initComponents();
        
        id = "anotacao"+java.util.UUID.randomUUID().toString();
        
        submodulografico = smg;
        xyannotation = anot;
    }
    
    public void renomearitem(String novonome)
    {
        jLabelNomeItemAnotacao.setText(novonome);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanelSub = new javax.swing.JPanel();
        jLabelNomeItemAnotacao = new javax.swing.JLabel();
        jLabelRemoverAnotacao = new javax.swing.JLabel();
        jLabelAbrirJanelaRenomearItemAnotacao = new javax.swing.JLabel();

        setBackground(new java.awt.Color(155, 155, 155));

        jPanelSub.setBackground(new java.awt.Color(55, 55, 55));

        jLabelNomeItemAnotacao.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNomeItemAnotacao.setText("Nova Anotação");

        jLabelRemoverAnotacao.setForeground(new java.awt.Color(255, 0, 0));
        jLabelRemoverAnotacao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRemoverAnotacao.setText(":");
        jLabelRemoverAnotacao.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jLabelRemoverAnotacaoMouseClicked(evt);
            }
        });

        jLabelAbrirJanelaRenomearItemAnotacao.setForeground(new java.awt.Color(255, 255, 125));
        jLabelAbrirJanelaRenomearItemAnotacao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAbrirJanelaRenomearItemAnotacao.setText(":");
        jLabelAbrirJanelaRenomearItemAnotacao.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jLabelAbrirJanelaRenomearItemAnotacaoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelSubLayout = new javax.swing.GroupLayout(jPanelSub);
        jPanelSub.setLayout(jPanelSubLayout);
        jPanelSubLayout.setHorizontalGroup(
            jPanelSubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSubLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNomeItemAnotacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelAbrirJanelaRenomearItemAnotacao, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelRemoverAnotacao, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelSubLayout.setVerticalGroup(
            jPanelSubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSubLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNomeItemAnotacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelSubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelRemoverAnotacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelAbrirJanelaRenomearItemAnotacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelSub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelSub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelAbrirJanelaRenomearItemAnotacaoMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLabelAbrirJanelaRenomearItemAnotacaoMouseClicked
    {//GEN-HEADEREND:event_jLabelAbrirJanelaRenomearItemAnotacaoMouseClicked
        mierframes.mfrenomearitemanotacao mfrig = new mierframes.mfrenomearitemanotacao(this);
        mfrig.show();
    }//GEN-LAST:event_jLabelAbrirJanelaRenomearItemAnotacaoMouseClicked

    private void jLabelRemoverAnotacaoMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLabelRemoverAnotacaoMouseClicked
    {//GEN-HEADEREND:event_jLabelRemoverAnotacaoMouseClicked
        submodulografico.removerAnotacao(this);
    }//GEN-LAST:event_jLabelRemoverAnotacaoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelAbrirJanelaRenomearItemAnotacao;
    public javax.swing.JLabel jLabelNomeItemAnotacao;
    private javax.swing.JLabel jLabelRemoverAnotacao;
    private javax.swing.JPanel jPanelSub;
    // End of variables declaration//GEN-END:variables
}
