/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames.analisadorasset.grafico;


/**
 *
 * @author lucasmeyer
 */
public class adicionarsimbolo extends javax.swing.JFrame
{
    public static panels.analisadorasset.grafico.submodulografico submodulograficopai;
    
    /**
     * Creates new form WindowAdicionarSimbolo
     */
    public adicionarsimbolo(panels.analisadorasset.grafico.submodulografico smodpai)
    {
        initComponents();
        
        submodulograficopai = smodpai;
        
        modellistasimbolosencontrados = new javax.swing.DefaultListModel();
        jlistSimbolosEncontrados.setModel(modellistasimbolosencontrados);
    }

    javax.swing.DefaultListModel modellistasimbolosencontrados;
    void procurarsimbolosemostrarnalista()
    {
        modellistasimbolosencontrados.removeAllElements();
        
        java.util.List<String> simbolosencontradosiex = 
                submodulograficopai.aassetpai.iaassetpai.tprincipalpai.msapicomms.receberlistasimbolosiexprocura(jtfProcurarSimbolo.getText());
        for (int i = 0; i < simbolosencontradosiex.size(); i++)
        {
            modellistasimbolosencontrados.addElement(simbolosencontradosiex.get(i));
        }
        
        java.util.List<String> simbolosencontradosav = 
                submodulograficopai.aassetpai.iaassetpai.tprincipalpai.msapicomms.receberlistasimbolosavprocura(jtfProcurarSimbolo.getText());
        for (int i = 0; i < simbolosencontradosav.size(); i++)
        {
            modellistasimbolosencontrados.addElement(simbolosencontradosav.get(i));
        }
        
        jlistSimbolosEncontrados.setSelectedIndex(0);
    }
    
    void adicionarsimboloprograma()
    {
        String simboloatual = ((String)modellistasimbolosencontrados.getElementAt(jlistSimbolosEncontrados.getSelectedIndex())).split(" - ")[0];
        
        submodulograficopai.adicionarsimboloaotextboxsubmodulo(simboloatual);
        this.dispose();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanelFundo = new javax.swing.JPanel();
        jPanelFundo2 = new javax.swing.JPanel();
        jLabelProcurar = new javax.swing.JLabel();
        jtfProcurarSimbolo = new javax.swing.JTextField();
        jbProcurarSimbolo = new javax.swing.JButton();
        jbAdicionarSimbolo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlistSimbolosEncontrados = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Search for Symbol");

        jPanelFundo.setBackground(new java.awt.Color(55, 55, 55));

        jPanelFundo2.setBackground(new java.awt.Color(120, 120, 120));

        jLabelProcurar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelProcurar.setText("Search:");

        jbProcurarSimbolo.setText("OK");
        jbProcurarSimbolo.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jbProcurarSimboloActionPerformed(evt);
            }
        });

        jbAdicionarSimbolo.setText("Add");
        jbAdicionarSimbolo.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jbAdicionarSimboloActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jlistSimbolosEncontrados);

        javax.swing.GroupLayout jPanelFundo2Layout = new javax.swing.GroupLayout(jPanelFundo2);
        jPanelFundo2.setLayout(jPanelFundo2Layout);
        jPanelFundo2Layout.setHorizontalGroup(
            jPanelFundo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFundo2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFundo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanelFundo2Layout.createSequentialGroup()
                        .addComponent(jLabelProcurar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfProcurarSimbolo, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbProcurarSimbolo))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFundo2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbAdicionarSimbolo)))
                .addContainerGap())
        );
        jPanelFundo2Layout.setVerticalGroup(
            jPanelFundo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFundo2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFundo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelProcurar)
                    .addComponent(jtfProcurarSimbolo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbProcurarSimbolo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbAdicionarSimbolo)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelFundoLayout = new javax.swing.GroupLayout(jPanelFundo);
        jPanelFundo.setLayout(jPanelFundoLayout);
        jPanelFundoLayout.setHorizontalGroup(
            jPanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFundoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelFundo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelFundoLayout.setVerticalGroup(
            jPanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFundoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelFundo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFundo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jPanelFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(3, 3, 3))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbProcurarSimboloActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jbProcurarSimboloActionPerformed
    {//GEN-HEADEREND:event_jbProcurarSimboloActionPerformed
        procurarsimbolosemostrarnalista();
    }//GEN-LAST:event_jbProcurarSimboloActionPerformed

    private void jbAdicionarSimboloActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jbAdicionarSimboloActionPerformed
    {//GEN-HEADEREND:event_jbAdicionarSimboloActionPerformed
        adicionarsimboloprograma();
    }//GEN-LAST:event_jbAdicionarSimboloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(adicionarsimbolo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(adicionarsimbolo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(adicionarsimbolo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(adicionarsimbolo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new adicionarsimbolo(submodulograficopai).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelProcurar;
    private javax.swing.JPanel jPanelFundo;
    private javax.swing.JPanel jPanelFundo2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAdicionarSimbolo;
    private javax.swing.JButton jbProcurarSimbolo;
    private javax.swing.JList<String> jlistSimbolosEncontrados;
    private javax.swing.JTextField jtfProcurarSimbolo;
    // End of variables declaration//GEN-END:variables
}
