/*
 * Copyright (C) 2019 Lucas Meyer
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package analisadorasset.submoduloofflinetrader;

/**
 *
 * @author lucasmeyer
 */
public class panel_itemtransacao extends javax.swing.JPanel
{
    //item utilizado para mostrar anotacoes introduzidas no grafico
    
    //submodulo grafico ao qual este item anotacao pertence
    public mierclasses.mcofflinetransaction offlinetransactionassociada;
    
    //construtor nova anotacao
    public panel_itemtransacao(mierclasses.mcofflinetransaction otransaction)
    {
        initComponents();

        offlinetransactionassociada = otransaction;
        
        jLabelID.setText(offlinetransactionassociada.idstr);
        
        if (offlinetransactionassociada.tipostr.equals("depositobase"))
            jLabelTipoTransacao.setText("Base Deposit");
        else if (offlinetransactionassociada.tipostr.equals("depositocotacao"))
            jLabelTipoTransacao.setText("Quote Deposit");
        else if (offlinetransactionassociada.tipostr.equals("saquebase"))
            jLabelTipoTransacao.setText("Base Withdraw");
        else if (offlinetransactionassociada.tipostr.equals("saquecotacao"))
            jLabelTipoTransacao.setText("Quote Withdraw");
        else if (offlinetransactionassociada.tipostr.equals("compra")) 
            jLabelTipoTransacao.setText("Buy");
        else if (offlinetransactionassociada.tipostr.equals("venda")) 
            jLabelTipoTransacao.setText("Sell");
        
        if (offlinetransactionassociada.preco_tradestr.equals("(NN)"))
            jLabelPrecoTransacao.setText("");
        else
            jLabelPrecoTransacao.setText(String.format( "%.8f",offlinetransactionassociada.preco_traded));
        
        jLabelQuantidadeTransacao.setText(String.format( "%.8f",offlinetransactionassociada.quantidaded));
        
        jLabelTimestampTransacao.setText(offlinetransactionassociada.timestampdate.toGMTString());
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanelSub = new javax.swing.JPanel();
        jLabelID = new javax.swing.JLabel();
        jLabelTipoTransacao = new javax.swing.JLabel();
        jLabelPrecoTransacao = new javax.swing.JLabel();
        jLabelQuantidadeTransacao = new javax.swing.JLabel();
        jLabelTimestampTransacao = new javax.swing.JLabel();

        setBackground(new java.awt.Color(155, 155, 155));

        jPanelSub.setBackground(new java.awt.Color(55, 55, 55));

        jLabelID.setForeground(new java.awt.Color(0, 153, 153));
        jLabelID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelID.setText("IDTransacao");
        jLabelID.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                jLabelIDMousePressed(evt);
            }
        });

        jLabelTipoTransacao.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTipoTransacao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTipoTransacao.setText("TipoTransacao");

        jLabelPrecoTransacao.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPrecoTransacao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPrecoTransacao.setText("PrecoTransacao");

        jLabelQuantidadeTransacao.setForeground(new java.awt.Color(255, 255, 255));
        jLabelQuantidadeTransacao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelQuantidadeTransacao.setText("QuantidadeTransacao");

        jLabelTimestampTransacao.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTimestampTransacao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTimestampTransacao.setText("TimestampTransacao");

        javax.swing.GroupLayout jPanelSubLayout = new javax.swing.GroupLayout(jPanelSub);
        jPanelSub.setLayout(jPanelSubLayout);
        jPanelSubLayout.setHorizontalGroup(
            jPanelSubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSubLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelID, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 219, Short.MAX_VALUE)
                .addComponent(jLabelTipoTransacao, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelPrecoTransacao, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelQuantidadeTransacao, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelTimestampTransacao, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelSubLayout.setVerticalGroup(
            jPanelSubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSubLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelID, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPrecoTransacao, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTipoTransacao, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTimestampTransacao, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelQuantidadeTransacao, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelSub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelSub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelIDMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLabelIDMousePressed
    {//GEN-HEADEREND:event_jLabelIDMousePressed
        mierclasses.mcfuncoeshelper.setarclipboard(jLabelID.getText());
        mierclasses.mcfuncoeshelper.mostrarmensagem("Transaction ID copied to clipboard.");
    }//GEN-LAST:event_jLabelIDMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jLabelID;
    public javax.swing.JLabel jLabelPrecoTransacao;
    public javax.swing.JLabel jLabelQuantidadeTransacao;
    public javax.swing.JLabel jLabelTimestampTransacao;
    public javax.swing.JLabel jLabelTipoTransacao;
    private javax.swing.JPanel jPanelSub;
    // End of variables declaration//GEN-END:variables
}
